server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inspection?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ruifeng.inspect.entity.*
